import { Voting } from "./types";
import Profile from "../../../assets/icons/Profile.svg";

export const DEFAULT_Voting: Voting = {
    totalCount: 6,
    rooms: [
        {
            tripPlanId: 1,
            roomId: 2,
            masterId: 2,
            roomName: "가족 여행",
            location: "제주도",
            totalMembers: 5,
            remainingTime: "SIX_HOURS",
            completedVotes: 2,
            profileImageUrls: [Profile, Profile, Profile, Profile, Profile],
            createdAt: "2025-02-21T04:20:08.696Z",
            tripPlanType: "SCHEDULE",
            latitude: 33.4996,
            longitude: 126.5312,
        },
        {
            tripPlanId: 2,
            roomId: 2,
            masterId: 2,
            roomName: "가족 여행",
            location: "제주도",
            totalMembers: 5,
            remainingTime: "THIRTY_MINUTES",
            completedVotes: 2,
            profileImageUrls: [Profile, Profile, Profile, Profile, Profile],
            createdAt: "2025-02-17T02:20:08.696Z",
            tripPlanType: "SCHEDULE",
            latitude: 33.4996,
            longitude: 126.5312,
        },
        {
            tripPlanId: 3,
            roomId: 3,
            masterId: 3,
            roomName: "커플 여행",
            location: "서울",
            totalMembers: 2,
            remainingTime: "FOUR_HOURS",
            completedVotes: 1,
            profileImageUrls: [Profile, Profile],
            createdAt: "2025-02-18T16:20:08.696Z",
            tripPlanType: "SCHEDULE",
            latitude: 37.5665,
            longitude: 126.978,
        },
        {
            tripPlanId: 4,
            roomId: 4,
            masterId: 4,
            roomName: "비즈니스 여행",
            location: "대전",
            totalMembers: 3,
            remainingTime: "SIX_HOURS",
            completedVotes: 2,
            profileImageUrls: [Profile, Profile, Profile],
            createdAt: "2025-02-18T16:20:08.696Z",
            tripPlanType: "SCHEDULE",
            latitude: 36.3504,
            longitude: 127.3845,
        },
    ],
};
