export const DEFAULT_Voting = {
    totalCount: 2,
    rooms: [
        {
            tripPlanId: 1,
            roomId: 1,
            masterId: 1,
            roomName: "친구들과의 여행",
            location: "부산",
            totalMembers: 4,
            remainingTime: "SIXTY_MINUTES",
            completedVotes: 3,
            profileImageUrls: ["Images.com", "Images.com", "Images.com", "Images.com"],
            createdAt: "2025-02-14T04:20:08.696Z",
            tripPlanType: "COURSE",
            latitude: 123.3213,
            longitude: 20.12121,
        },
        {
            tripPlanId: 2,
            roomId: 2,
            masterId: 2,
            roomName: "가족 여행",
            location: "제주도",
            totalMembers: 5,
            remainingTime: "THIRTY_MINUTES",
            completedVotes: 2,
            profileImageUrls: ["Images.com", "Images.com", "Images.com", "Images.com", "Images.com"],
            createdAt: "2025-02-14T04:20:08.696Z",
            tripPlanType: "SCHEDULE",
            latitude: 123.3213,
            longitude: 20.12121,
        },
    ],
};
