export const DEFAULT_TripInfo = {
  tripId: 2001, 
  roomId: 1001,  
  masterId: 5001,  
  location: "경기도 부천시 역곡동 45-18",
  description: "관광 명소 방문 위주로 진행 예정",
  imageUrl: "https://example.com/images/1.jpg",
  customLocation: "제주시",
  price: "20만원",
  minDays: 3,
  maxDays: 7,
  month: 2,
  roomName: "여행가보자고",
  userCount: 5,
  userName: "고민균",
  masterName: "곰구마",
  voteLimitTime: "THIRTY_MINUTES",
  startDate: "2025-02-01",
  endDate: "2025-02-07",
};
